### ISSUE TITLE
UI update breaks extension

### ISSUE THREAD

**Issue by yeeterlol** [Flkalas/TwitterMediaAssist#18]
**Problem**
The new Twitter UI update deciding to screw around the extension and broke it.
**Tweet w/extension**
![image](https://user-images.githubusercontent.com/81702700/209458500-ea1ef4e0-2119-4777-8206-153ab42fe1bd.png)
**Tweet without extension**
![image](https://user-images.githubusercontent.com/81702700/209458504-f567e3cc-abd3-4109-a252-82a0ef2f7572.png)

**Comment by Novack** [comment]
Im getting this too.

**Comment by biast12** [comment]
@Flkalas would love for this to get fixed

**Comment by Kroissan** [comment]
![image](https://user-images.githubusercontent.com/66138267/210132638-0d0c2225-9a47-4e6c-bd7a-dabc6da6fcda.png)
Also in feed, it duplicate the like button instead of the share button.
I have a fix ready, doing a PR

**Comment by yeeterlol** [comment]
![image](https://user-images.githubusercontent.com/81702700/211942930-b4f2348f-75f4-4592-ac72-64722904ac5d.png)
It got fixed sorta but the feed is still broken.

**Comment by Kroissan** [comment]
> ![image](https://user-images.githubusercontent.com/81702700/211942930-b4f2348f-75f4-4592-ac72-64722904ac5d.png) It got fixed sorta but the feed is still broken.

Do you have a screenshot ? Wich browser do you use ?
