### ISSUE TITLE
Twitter new UI problem

### ISSUE THREAD

**Issue by Mas99** [Flkalas/TwitterMediaAssist#22]
Hi

The twitter new UI is causing this app to fail. when you click on download, it re-directs the page to analytics of that post

**Comment by DealsBeam** [comment]
The extension hasn't been updated since 2021, you might want to look for an alternative.

**Comment by Mas99** [comment]
There is no alternative... Any suggestion ?

**Comment by DealsBeam** [comment]
There's one called Media Harvest Twitter Media Downloader

**Comment by nowata** [comment]
> There's one called Media Harvest Twitter Media Downloader

Very useful information, thks for the recommendation!

**Comment by Flkalas** [comment]
would it fixed? I fixed it in firefox version my self but not chrome. some people fix by self and i merged them.
