### ISSUE TITLE
All buttons removed when extension is enabled in firefox

### ISSUE THREAD

**Issue by ProtoVee-MK1** [Flkalas/TwitterMediaAssist#24]
When using the firefox version of the extension, all of the buttons below a tweet (like, retweet, etc.) disappear.

Enabled
![image](https://github.com/Flkalas/TwitterMediaAssist/assets/11646530/a695eaf5-4cc1-42a7-80ce-c07749885df3)

Disabled
![image](https://github.com/Flkalas/TwitterMediaAssist/assets/11646530/874a6ced-bf8d-4564-b0e0-f67f6250fcd9)

**Comment by Flkalas** [comment]
I see. I will check on. It seems that it can be completed by 22:00 on July 13th, KST.

**Comment by Bunny-Head** [comment]
I came here to report the same so as it's done, I will take the chance and say thank you for this awesome plug-in!

**Comment by Flkalas** [comment]
Fixed with commit https://github.com/Flkalas/TwitterMediaAssist/commit/65e26528937c87342e3960556a06d076baa9ec14 
Updating to Version 3.0.7 will fix it.
