### ISSUE TITLE
Problem when downloading tweet media

### ISSUE THREAD

**Issue by Neatro** [Flkalas/TwitterMediaAssist#26]
Cannot download tweet media, instead the download fails and says it's a .txt file.

**Comment by Flkalas** [comment]
👀

**Comment by BBleae** [comment]
I encountered the same issue. You might consider merging Pull Request #28, which temporarily fixes this problem.

**Comment by Flkalas** [comment]
This problem will fix with 3.2.1. I submitted. Firefox version already has applied
