### ISSUE TITLE
Download button spacing

### ISSUE THREAD

**Issue by aubymori** [Flkalas/TwitterMediaAssist#31]
Since yesterday, the download button has had its left margin removed, resulting in it and the share button being squished together.
![image](https://github.com/Flkalas/TwitterMediaAssist/assets/44238627/c4b43b3a-b7ff-4661-a682-d6654a2c9716)

**Comment by Flkalas** [comment]
I see. I will do it until 12:00 UTC on the 29th.

**Comment by Flkalas** [comment]
sorry to late https://github.com/Flkalas/TwitterMediaAssist/commit/94036b39b2e7deeb12fa3cf32218eec624562a29
it fixed.
