### ISSUE TITLE
I'd like to have a patch, please.

### ISSUE THREAD

**Issue by HarangSky** [Flkalas/TwitterMediaAssist#32]
If you download two videos in one tweet, only the first video will be downloaded. I want to download the first and second videos.

**Comment by Flkalas** [comment]
I cannot upload two video in one tweet on web version. Could you give me a example tweet url to analyze and test?

**Comment by HarangSky** [comment]
If it is the first photo and the second video, only the first photo can be downloaded, and the second video cannot be downloaded
If it is the first video and the second picture, only the first video can be downloaded, and the second video cannot be downloaded
If it is the first video and the second video, only the first video can be downloaded, and the second video cannot be downloaded
Please check it, and please understand that there is no example address.

**Comment by Flkalas** [comment]
OK. Without an example tweet, I can't test whether the modifications work properly. Therefore, even if you think you have made the appropriate corrections, you may not know whether they have been corrected. Therefore, please understand even if it cannot be corrected.

**Comment by yehwankim23** [comment]
@Flkalas You can find some example tweets here: https://twitter.com/yehwankim23

**Comment by Flkalas** [comment]
> @Flkalas You can find some example tweets here: https://twitter.com/yehwankim23

@yehwankim23 Thank you for your cooperation. We will fix it as soon as possible.

**Comment by HarangSky** [comment]
@yehwankim23 도와주셔서 감사합니다. Thank you

**Comment by HarangSky** [comment]
@Flkalas I think we need to keep in mind three or four videos, not two.

**Comment by yehwankim23** [comment]
I added a new example tweet for 4 videos

- Image + Image: 👍
- Image + Video: only video as `.ts`
- Video + Image: only video
- Video + Video: only the first video
- 4 videos: only the first video

**Comment by HarangSky** [comment]
@yehwankim23 Thank you for your help.

**Comment by Flkalas** [comment]
A fix will be updated soon.
https://github.com/Flkalas/TwitterMediaAssist/commit/5213775c47ea995596267b2fb02a5d8b2021bf5c
