### ISSUE TITLE
Twitter no longer works and is now X.com only 

### ISSUE THREAD

**Issue by Blanko2** [Flkalas/TwitterMediaAssist#36]
Would it be possible to update the extension to point to x.com?

**Comment by LadyHaley** [comment]
yeah any twitter domain will redirect to x dot com

**Comment by Flkalas** [comment]
All right. I will work on it and upload it.

**Comment by Flkalas** [comment]
The issue was resolved with the following commit: 
https://github.com/Flkalas/TwitterMediaAssist/commit/9f087b601fbac7b007f030d3d0a9b87f27b1d04d 

A new version has been submitted to each store and will be reflected within one day.
