### ISSUE TITLE
Can no longer download from Private Profiles

### ISSUE THREAD

**Issue by TOOMANYENEMIES64** [Flkalas/TwitterMediaAssist#40]
Before the swap to X the download button was greyed out but I could still download. Now with the recent Chrome update which adds X functionality the button remains but it no longer does download

**Comment by Flkalas** [comment]
The cause has been analyzed and I will be uploading a patched version soon.

**Comment by Flkalas** [comment]
The issue has been resolved with https://github.com/Flkalas/TwitterMediaAssist/commit/2f427b683378829542a92cd5ef35ed84edb76bca
