### ISSUE TITLE
When there is both a video and an image, only the image is downloaded

### ISSUE THREAD

**Issue by MoonDragon-MD** [Flkalas/TwitterMediaAssist#41]
Hi, first of all thank you for this great add-on, I discovered it six months ago!!! Until last week I used it without problems, now the arrow to download doesn't show, I just updated to version 3.2.4 (on Firefox 125.0.3).

What could this be due to?
Can it be fixed?

Thanks in advance

**Comment by MoonDragon-MD** [comment]
Now the browser offered me a new update (3.2.5), and it is working again, Thanks!!
But there is one thing that could be fixed: when there is both a video and an image, only the image is downloaded

**Comment by Flkalas** [comment]
Yes, we will investigate and take action.

**Comment by Flkalas** [comment]
I didn't see any problems with my test tweets. 

Could you please check the issue again? The link is below.
https://x.com/lesenic/status/1793612756433936530

**Comment by MoonDragon-MD** [comment]
> I didn't see any problems with my test tweets.
> 
> Could you please check the issue again? The link is below. https://x.com/lesenic/status/1793612756433936530

Hi, after upgrading to version 3.2.6 and going to the link you provided, I clicked the download button and this time it worked for all four files. Also I tried other mixed tweets with images and videos and also with only 4 images.
It works on all of them.
Thanks again for your work and helpfulness
