### ISSUE TITLE
Addon isn't active for x.com domain

### ISSUE THREAD

**Issue by ostnr** [Flkalas/TwitterMediaAssist#42]
Addon "can't read or change data on this site" probably because x.com domain is not supported?

**Comment by Flkalas** [comment]
I remember that the update to support the x.com domain was made in 3.2.5. 
Here is the corresponding commit that fixed the issue: https://github.com/Flkalas/TwitterMediaAssist/commit/0762c24062b6155f21a328166144b2f1a6991aa1

Is this problem still reproducible? Can you provide a screenshot or other information?

**Comment by ostnr** [comment]
actually that was only my problem. im on 3.2.4 but checking for updates doesn't do anything. but on the firefox addons page there is already 3.2.6.
- Re-added the addon and now it works!

**Comment by Flkalas** [comment]
Thank you for checking. Close the issue.
