### ISSUE TITLE
Mutation event support disabled after Chrome 127 and breaks extension

### ISSUE THREAD

**Issue by ponkotsuaoi** [Flkalas/TwitterMediaAssist#44]
jquery-3.3.1.min.js:2  [Deprecation] Listener added for a 'DOMNodeInserted' mutation event. Support for this event type has been removed, and this event will no longer be fired. See https://chromestatus.com/feature/5083947249172480 for more information.
add @ jquery-3.3.1.min.js:2
(anonymous) @ jquery-3.3.1.min.js:2
each @ jquery-3.3.1.min.js:2
each @ jquery-3.3.1.min.js:2
De @ jquery-3.3.1.min.js:2
on @ jquery-3.3.1.min.js:2
(anonymous) @ twitter_video_assist_client.js:9
![msedge_FIIILvVk7M](https://github.com/user-attachments/assets/249c88fa-1b80-407d-883c-27e3b6be5e89)

**Comment by Flkalas** [comment]
ok i see

**Comment by Flkalas** [comment]
https://github.com/Flkalas/TwitterMediaAssist/commit/e29844c63a1d002d65ed6fb8b806b6e5078152f5

fixed it. 
thx to notice.
