### ISSUE TITLE
Image file names are in the wrong order.

### ISSUE THREAD

**Issue by f11894** [Flkalas/TwitterMediaAssist#6]
I want to download readable file name :☑

Where it should be 1,2,3,4, it's now 1,3,2,4.
https://twitter.com/euphoria_91418/status/1240053526635499520

This behavior is very inconvenient when downloading comics.
https://twitter.com/teen0801/status/1243834184977661953
https://twitter.com/Qevryo/status/1243157132133855232

**Comment by Flkalas** [comment]
Fixed in v3.0.3

**Comment by f11894** [comment]
Thank you so much.
